- name: "configure {{ component }} server"
  hosts: all
  connection: local
  vars_files: 
  - "variables-{{ env }}.yaml"   #if we pass dev then dev variables will load
  become: yes
  roles:
  - "{{ component }}"